version: '3'

services:
    mongodb:
        build: mongodb/
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=lappis
            - MONGO_INITDB_ROOT_PASSWORD=lappis

        volumes:
            - ./data/mongodb:/data/db
        networks:
            - stack

    metabase:
        build: metabase/
        ports:
            - "3000:3000"
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
        volumes:
            - ./data/metabase:/metabase-data
        networks:
            - stack
        depends_on:
            - mongodb

networks:
    stack:
        driver: bridge
