name: Build and publish pyhton package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-poetry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python 3.8 enviroment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8

      - run: |
          poetry config pypi-token.pypi pypi-AgEIcHlwaS5vcmcCJGYyZjdjYjlhLTI4MzctNDY0Zi04MzVjLTU5MmYxMzFkY2U0NgACKlszLCIyNTcxYjQzMy04ZDI2LTQ5YmUtYTIzZS03M2FiMDA4ZDdjZWYiXQAABiCPo1gYrocJ_KHYyXqzhTjqoAVFrxrZLLsn4ka9w7YnWw
          poetry build
          poetry publish
          
          
