name: Build and publish pyhton package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-poetry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python 3.8 enviroment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8

      - run: poetry config pypi-token.pypi ${{ PYPI_TOKEN }}
      - run: poetry build
      - run: poetry publish
          
          
