name: Build and test pyhton package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ambient-docker:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --build -d
      
  build-poetry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python 3.8 enviroment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8

      - run: poetry build

  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test
        run: |
          pytest tests/
  
  run-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Linting the code with pylint
        run: |
          pylint $(git ls-files '*.py')
          
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
